FROM flink:1.18-scala_2.12

ADD https://repo1.maven.org/maven2/org/apache/flink/flink-connector-filesystem/1.18.0/flink-connector-filesystem-1.18.0.jar /opt/flink/lib/
ADD https://repo1.maven.org/maven2/org/apache/flink/flink-connector-elasticsearch7/1.18.0/flink-connector-elasticsearch7-1.18.0.jar /opt/flink/lib/
ADD https://repo1.maven.org/maven2/org/elasticsearch/client/elasticsearch-rest-high-level-client/7.10.2/elasticsearch-rest-high-level-client-7.10.2.jar /opt/flink/lib/

